//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarento.Common.Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) 
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tarento.Common.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default area can not be added to the configured areas collection..
        /// </summary>
        internal static string AddedDefaultDiagnosticsAreaToCollection {
            get {
                return ResourceManager.GetString("AddedDefaultDiagnosticsAreaToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be a boolean..
        /// </summary>
        internal static string ArgumentMustBeBoolean {
            get {
                return ResourceManager.GetString("ArgumentMustBeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be a datetime..
        /// </summary>
        internal static string ArgumentMustBeDateTime {
            get {
                return ResourceManager.GetString("ArgumentMustBeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be a guid..
        /// </summary>
        internal static string ArgumentMustBeGuid {
            get {
                return ResourceManager.GetString("ArgumentMustBeGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be a number..
        /// </summary>
        internal static string ArgumentMustBeNumber {
            get {
                return ResourceManager.GetString("ArgumentMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be numeric..
        /// </summary>
        internal static string ArgumentMustBeNumeric {
            get {
                return ResourceManager.GetString("ArgumentMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must not be empty or null..
        /// </summary>
        internal static string ArgumentMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to cache a null reference.
        /// </summary>
        internal static string AttemptToCacheNullReference {
            get {
                return ResourceManager.GetString("AttemptToCacheNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Category &apos;{0}&apos; was not found in the diagnostic categories collections..
        /// </summary>
        internal static string CategoryNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("CategoryNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configsetting with key &apos;{0}&apos; could not be set &apos;{1}&apos; with type &apos;{2}&apos;. The technical exception was: {3}: {4}.
        /// </summary>
        internal static string ConfigSettingNotSet {
            get {
                return ResourceManager.GetString("ConfigSettingNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area being added already exists \n\t Value: &apos;{0}&apos;.
        /// </summary>
        internal static string DiagnosticsAreaCollectionAreaExists {
            get {
                return ResourceManager.GetString("DiagnosticsAreaCollectionAreaExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to save areas configuration without setting configuration manager.
        /// </summary>
        internal static string DiagnosticsAreaCollectionSaveWithNoConfig {
            get {
                return ResourceManager.GetString("DiagnosticsAreaCollectionSaveWithNoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DiagnosticsCategory exists, only one entry for a category per area. Value: &apos;{0}&apos;.
        /// </summary>
        internal static string DiagnosticsCategoryExists {
            get {
                return ResourceManager.GetString("DiagnosticsCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing tot the Trace Log, trace message:{0}.
        /// </summary>
        internal static string ErrorWritingTrace {
            get {
                return ResourceManager.GetString("ErrorWritingTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        internal static string ExceptionHandlerAdditionalInformation {
            get {
                return ResourceManager.GetString("ExceptionHandlerAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Details.
        /// </summary>
        internal static string ExceptionHandlerHideDetails {
            get {
                return ResourceManager.GetString("ExceptionHandlerHideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ExceptionHandlerShowDetails {
            get {
                return ResourceManager.GetString("ExceptionHandlerShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in processing. If the problem persists, please contact help desk for assistance..
        /// </summary>
        internal static string ExceptionHandlerTitle {
            get {
                return ResourceManager.GetString("ExceptionHandlerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed deserializing key:&apos;{0}&apos;, serialized data: &apos;{1}&apos;.
        /// </summary>
        internal static string FailedDeserialization {
            get {
                return ResourceManager.GetString("FailedDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category name should be formatted as a path (area/category), invalid format: {0}.
        /// </summary>
        internal static string InvalidCategoryFormat {
            get {
                return ResourceManager.GetString("InvalidCategoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config setting with key &apos;{0}&apos; could not be retrieved. The configured value could not be converted from &apos;{1}&apos; to an instance of &apos;{2}&apos;. The technical exception was: {3}: {4}.
        /// </summary>
        internal static string InvalidConfigSetting {
            get {
                return ResourceManager.GetString("InvalidConfigSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; must be between 1 and &apos;{1}&apos; in length.  Key Length: &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidKeyLength {
            get {
                return ResourceManager.GetString("InvalidKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; cannot be used. Key&apos;s may not be prefixed with the text &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidKeyPrefix {
            get {
                return ResourceManager.GetString("InvalidKeyPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; cannot be used. Key&apos;s may not be suffixed with the text &apos;{1}&apos; because this is used by the SPSitePropertyBag to differentiate between properties of the SPWeb and the SPSite..
        /// </summary>
        internal static string InvalidKeySuffix {
            get {
                return ResourceManager.GetString("InvalidKeySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no value configured for key &apos;{0}&apos; in a propertyBag..
        /// </summary>
        internal static string KeyNotConfigured {
            get {
                return ResourceManager.GetString("KeyNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occurred while writing messages into the log..
        /// </summary>
        internal static string LoggingExceptionMessage1 {
            get {
                return ResourceManager.GetString("LoggingExceptionMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\nThe error while writing to the EventLog was:.
        /// </summary>
        internal static string LoggingExceptionMessage2 {
            get {
                return ResourceManager.GetString("LoggingExceptionMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n Orginal logged message was:.
        /// </summary>
        internal static string LoggingExceptionMessage3 {
            get {
                return ResourceManager.GetString("LoggingExceptionMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;br /&amp;gt;{0}{1}. Open the tool pane to configure Web Part properties.&amp;lt;br /&amp;gt;&amp;lt;br /&amp;gt;.
        /// </summary>
        internal static string MissingSettingExceptionMessage {
            get {
                return ResourceManager.GetString("MissingSettingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required setting.
        /// </summary>
        internal static string MissingSettingExceptionTitle {
            get {
                return ResourceManager.GetString("MissingSettingExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;br /&amp;gt;The Web Part has not been configured correctly{0}. &amp;lt;a href=\&quot;javascript:MSOTlPn_ShowToolPane2Wrapper(&apos;Edit&apos;,&apos;129&apos;,&apos;{1}&apos;)\&quot;&amp;gt;Open the tool pane&amp;lt;/a&amp;gt; to configure Web Part properties.&amp;lt;br /&amp;gt;&amp;lt;br /&amp;gt;.
        /// </summary>
        internal static string NotConfiguredExceptionId {
            get {
                return ResourceManager.GetString("NotConfiguredExceptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;br /&amp;gt;The Web Part has not been configured correctly{0}. Open the tool pane to configure Web Part properties.&amp;lt;br /&amp;gt;&amp;lt;br /&amp;gt;.
        /// </summary>
        internal static string NotConfiguredExceptionNoId {
            get {
                return ResourceManager.GetString("NotConfiguredExceptionNoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property bag for level &apos;{0}&apos; is not accessible in the current context..
        /// </summary>
        internal static string PropertyBagNotValidForContext {
            get {
                return ResourceManager.GetString("PropertyBagNotValidForContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPFarm was not found..
        /// </summary>
        internal static string SPFarmNotFound {
            get {
                return ResourceManager.GetString("SPFarmNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index value is not found in the collection: Collection &apos;{0}&apos; Value &apos;{1}&apos;.
        /// </summary>
        internal static string StringIndexOutOfRange {
            get {
                return ResourceManager.GetString("StringIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {1} cannot be assigned to variables of type {0}..
        /// </summary>
        internal static string TypesAreNotAssignable {
            get {
                return ResourceManager.GetString("TypesAreNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set value in hierarchical config.\n\tKey: &apos;{0}&apos;\n\tLevel: &apos;{1}&apos;\n\tValue: &apos;{2}&apos;.
        /// </summary>
        internal static string ValueSetInConfig {
            get {
                return ResourceManager.GetString("ValueSetInConfig", resourceCulture);
            }
        }
    }
}
